import { jsPDF } from "jspdf";
import { ConsultationReport } from "../types";

export const generatePDF = (report: ConsultationReport) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2) - 5; // Extra 5px buffer for safety
  let yPos = 20;

  // Color definitions matching the portal
  const colors = {
    teal: { r: 15, g: 118, b: 110 },
    violet: { r: 109, g: 40, b: 217 },
    emerald: { r: 4, g: 120, b: 87 },
    blue: { r: 29, g: 78, b: 216 },
    rose: { r: 190, g: 18, b: 60 },
    amber: { r: 180, g: 83, b: 9 },
    indigo: { r: 79, g: 70, b: 229 },
    slate: { r: 71, g: 85, b: 105 },
    slateLight: { r: 100, g: 116, b: 139 },
    slateDark: { r: 30, g: 41, b: 59 },
  };

  const setColor = (color: { r: number; g: number; b: number }) => {
    doc.setTextColor(color.r, color.g, color.b);
  };

  const checkPageBreak = (heightNeeded: number) => {
    if (yPos + heightNeeded > pageHeight - 20) {
      doc.addPage();
      yPos = 20;
    }
  };

  const drawRoundedRect = (x: number, y: number, w: number, h: number, r: number, color: { r: number; g: number; b: number }, fillOpacity: number = 0.1) => {
    doc.setFillColor(color.r, color.g, color.b);
    doc.setDrawColor(color.r, color.g, color.b);
    doc.roundedRect(x, y, w, h, r, r, 'F');
  };

  // ==================== HEADER ====================
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  setColor(colors.teal);
  doc.text("Medical Consultation Report", margin, yPos);
  yPos += 8;
  
  doc.setFontSize(10);
  setColor(colors.slateLight);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated on ${report.consultationDate}`, margin, yPos);
  yPos += 12;

  // ==================== PATIENT/DOCTOR INFO BOX ====================
  const infoBoxHeight = 22;
  doc.setFillColor(248, 250, 252); // slate-50
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.roundedRect(margin, yPos, contentWidth, infoBoxHeight, 3, 3, 'FD');
  
  // Doctor info
  doc.setFontSize(8);
  setColor(colors.slateLight);
  doc.setFont("helvetica", "bold");
  doc.text("DOCTOR", margin + 8, yPos + 7);
  doc.setFontSize(11);
  setColor(colors.slateDark);
  doc.setFont("helvetica", "normal");
  const doctorNameLines = doc.splitTextToSize(report.doctorName, contentWidth / 2 - 20);
  doc.text(doctorNameLines[0] || report.doctorName, margin + 8, yPos + 15);
  
  // Divider
  doc.setDrawColor(226, 232, 240);
  doc.line(pageWidth / 2, yPos + 4, pageWidth / 2, yPos + infoBoxHeight - 4);
  
  // Patient info
  doc.setFontSize(8);
  setColor(colors.slateLight);
  doc.setFont("helvetica", "bold");
  doc.text("PATIENT", pageWidth / 2 + 8, yPos + 7);
  doc.setFontSize(11);
  setColor(colors.slateDark);
  doc.setFont("helvetica", "normal");
  const patientNameLines = doc.splitTextToSize(report.patientName, contentWidth / 2 - 20);
  doc.text(patientNameLines[0] || report.patientName, pageWidth / 2 + 8, yPos + 15);
  
  yPos += infoBoxHeight + 12;

  // ==================== CLINICAL SUMMARY ====================
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  setColor(colors.teal);
  doc.text("Clinical Summary", margin, yPos);
  yPos += 8;
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  setColor(colors.slate);
  // Ensure font is set before calculating text wrap
  const summaryLines = doc.splitTextToSize(report.summary, contentWidth);
  checkPageBreak(summaryLines.length * 5 + 10);
  summaryLines.forEach((line: string, index: number) => {
    checkPageBreak(6);
    doc.text(line, margin, yPos);
    yPos += 5;
  });
  yPos += 12;

  // ==================== AI MEDICAL INSIGHTS ====================
  checkPageBreak(40);
  
  // Section header with violet color
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  setColor(colors.violet);
  doc.text("AI Medical Expert Analysis", margin, yPos);
  yPos += 10;

  // AI Disclaimer box
  const disclaimerText = "AI Disclaimer: This section is generated by AI based on the consultation context. It is for informational purposes only and should not replace professional medical advice.";
  doc.setFontSize(8);
  const disclaimerLines = doc.splitTextToSize(disclaimerText, contentWidth - 16);
  const disclaimerHeight = disclaimerLines.length * 4 + 8;
  
  doc.setFillColor(245, 243, 255); // violet-50
  doc.setDrawColor(221, 214, 254); // violet-200
  doc.roundedRect(margin, yPos, contentWidth + 5, disclaimerHeight, 2, 2, 'FD');
  
  setColor(colors.violet);
  doc.text(disclaimerLines, margin + 8, yPos + 6);
  yPos += disclaimerHeight + 10;

  // Possible Diagnosis
  checkPageBreak(25);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  setColor(colors.slateDark);
  doc.text("POSSIBLE DIAGNOSIS", margin, yPos);
  yPos += 7;
  
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  setColor(colors.slateDark);
  const diagnosisLines = doc.splitTextToSize(report.medicalInsights.possibleDiagnosis, contentWidth);
  diagnosisLines.forEach((line: string) => {
    checkPageBreak(6);
    doc.text(line, margin, yPos);
    yPos += 6;
  });
  yPos += 10;

  // Helper function for colored section lists with proper text wrapping
  const printColoredSection = (title: string, items: string[], color: { r: number; g: number; b: number }) => {
    if (items.length === 0) return;
    
    // Check page break for title
    checkPageBreak(20);
    
    // Section title with colored heading (matching portal colors)
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    setColor(color);
    doc.text(title.toUpperCase(), margin, yPos);
    yPos += 7;
    
    // Items - process each item with proper wrapping
    items.forEach(item => {
      // Set font BEFORE calculating split text - this is crucial
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      setColor(colors.slate);
      
      const maxWidth = contentWidth - 10; // Leave room for bullet indent
      const itemText = `• ${item}`;
      const itemLines = doc.splitTextToSize(itemText, maxWidth);
      
      // Draw each line individually with page break check
      itemLines.forEach((line: string, lineIndex: number) => {
        checkPageBreak(6);
        doc.text(line, margin + 5, yPos);
        yPos += 5;
      });
      yPos += 2; // Space between items
    });
    yPos += 8;
  };

  // AI Insights sections with matching colors from portal
  printColoredSection("Prevention", report.medicalInsights.prevention, colors.emerald);
  printColoredSection("Treatment & Cure", report.medicalInsights.treatment, colors.blue);
  printColoredSection("Recommended Medicines (AI)", report.medicalInsights.recommendedMedicines, colors.rose);
  printColoredSection("Lifestyle Changes", report.medicalInsights.lifestyleChanges, colors.amber);

  // ==================== INSIGHTS FROM OFFLINE RESEARCH ====================
  if (report.vectorDBInsights && report.vectorDBInsights.length > 0) {
    checkPageBreak(30);
    yPos += 5;
    
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    setColor(colors.indigo);
    doc.text("Insights from offline research", margin, yPos);
    yPos += 10;

    report.vectorDBInsights.forEach((insight, index) => {
      checkPageBreak(30);
      
      // Paper title
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      setColor(colors.slateDark);
      const titleLines = doc.splitTextToSize(insight.title, contentWidth - 30);
      titleLines.forEach((line: string) => {
        checkPageBreak(6);
        doc.text(line, margin + 5, yPos);
        yPos += 5;
      });
      
      // Relevance score
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      setColor(colors.indigo);
      doc.text(`Relevance: ${(insight.relevance * 100).toFixed(0)}%`, margin + 5, yPos);
      yPos += 7;
      
      // Excerpt
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      setColor(colors.slate);
      const excerptLines = doc.splitTextToSize(insight.excerpt + '...', contentWidth - 10);
      excerptLines.forEach((line: string) => {
        checkPageBreak(5);
        doc.text(line, margin + 5, yPos);
        yPos += 4;
      });
      yPos += 8;
    });
    yPos += 5;
  }

  // ==================== PRESCRIPTIONS ====================
  if (report.prescriptions.length > 0) {
    checkPageBreak(30);
    yPos += 5;
    
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    setColor(colors.teal);
    doc.text("Prescriptions (From Doctor)", margin, yPos);
    yPos += 10;
    
    report.prescriptions.forEach((rx) => {
      const medLines = doc.splitTextToSize(`• ${rx.medicine}`, contentWidth - 10);
      const instrLines = doc.splitTextToSize(`  ${rx.dosage} - ${rx.instructions}`, contentWidth - 15);
      const itemHeight = medLines.length * 5 + instrLines.length * 4 + 8;
      
      checkPageBreak(itemHeight);
      
      // Draw background for this prescription item
      doc.setFillColor(240, 253, 250); // teal-50
      doc.roundedRect(margin, yPos - 2, contentWidth, itemHeight, 2, 2, 'F');
      
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      setColor(colors.slateDark);
      doc.text(medLines, margin + 5, yPos + 3);
      yPos += medLines.length * 5 + 2;
      
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      setColor(colors.slateLight);
      doc.text(instrLines, margin + 10, yPos);
      yPos += instrLines.length * 4 + 6;
    });
    
    yPos += 10;
  }

  // ==================== TRANSCRIPT ====================
  checkPageBreak(30);
  doc.addPage();
  yPos = 20;
  
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  setColor(colors.slateDark);
  doc.text("Full Transcript", margin, yPos);
  yPos += 10;

  report.transcript.forEach((line) => {
    const textLines = doc.splitTextToSize(line.text, contentWidth - 5);
    const heightNeeded = textLines.length * 5 + 12;
    
    checkPageBreak(heightNeeded);
    
    // Speaker label with color
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    const isDoctor = line.speaker.toLowerCase().includes('doctor');
    setColor(isDoctor ? colors.teal : colors.indigo);
    doc.text(line.speaker.toUpperCase(), margin, yPos);
    yPos += 5;
    
    // Speech bubble background
    doc.setFillColor(248, 250, 252); // slate-50
    const bubbleHeight = textLines.length * 5 + 6;
    doc.roundedRect(margin, yPos - 2, contentWidth, bubbleHeight, 2, 2, 'F');
    
    // Text content
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    setColor(colors.slate);
    doc.text(textLines, margin + 5, yPos + 4);
    
    yPos += bubbleHeight + 5;
  });

  // ==================== FOOTER ====================
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    setColor(colors.slateLight);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin - 20, pageHeight - 10);
    doc.text("Generated by MediScribe AI", margin, pageHeight - 10);
  }

  doc.save(`Consultation_Report_${report.patientName.replace(/\s+/g, '_')}_${report.consultationDate.replace(/\//g, '-')}.pdf`);
};